### ISSUE TITLE
CRASH: Symbol not found: _clock_gettime

### ISSUE THREAD

**Issue by Sod-Almighty** [xor-gate/syncthing-macosx#164]
Syncthing fails to start its service, due to the following error:
```
2021-08-02 19:01:20.336 Syncthing[7417:49186232] Launching Syncthing daemon
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /Applications/Syncthing.app/Contents/Resources/syncthing/syncthing
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /Applications/Syncthing.app/Contents/Resources/syncthing/syncthing
  Expected in: /usr/lib/libSystem.B.dylib

SIGTRAP: trace trap
PC=0x7fff6789e075 m=0 sigcode=1

goroutine 0 [idle]:
runtime.walltime1(0x0, 0x0)
	runtime/sys_darwin.go:270 +0x4a fp=0xc0002635c0 sp=0xc000263588 pc=0x405b46a
runtime.walltime(...)
	runtime/time_nofake.go:23
time.now(0x0, 0xc000263628, 0x4010bb8)
	runtime/timestub.go:16 +0x25 fp=0xc0002635f0 sp=0xc0002635c0 pc=0x40717e5
time.Now(0x10000c000263601, 0xc000240aa0, 0xc000263648)
	time/time.go:1067 +0x26 fp=0xc000263618 sp=0xc0002635f0 pc=0x40d3d46
github.com/lucas-clemente/quic-go/internal/wire.init.1()
	github.com/lucas-clemente/quic-go@v0.19.3/internal/wire/transport_parameters.go:22 +0x26 fp=0xc000263658 sp=0xc000263618 pc=0x4891ea6
runtime.doInit(0x54b3ae0)
	runtime/proc.go:6309 +0xec fp=0xc0002637a8 sp=0xc000263658 pc=0x404a86c
runtime.doInit(0x54ae7e0)
	runtime/proc.go:6286 +0x72 fp=0xc0002638f8 sp=0xc0002637a8 pc=0x404a7f2
runtime.doInit(0x54b7580)
	runtime/proc.go:6286 +0x72 fp=0xc000263a48 sp=0xc0002638f8 pc=0x404a7f2
runtime.doInit(0x54b9660)
	runtime/proc.go:6286 +0x72 fp=0xc000263b98 sp=0xc000263a48 pc=0x404a7f2
runtime.doInit(0x54bb1c0)
	runtime/proc.go:6286 +0x72 fp=0xc000263ce8 sp=0xc000263b98 pc=0x404a7f2
runtime.doInit(0x54b8a20)
	runtime/proc.go:6286 +0x72 fp=0xc000263e38 sp=0xc000263ce8 pc=0x404a7f2
runtime.doInit(0x54ba320)
	runtime/proc.go:6286 +0x72 fp=0xc000263f88 sp=0xc000263e38 pc=0x404a7f2
runtime.main()
	runtime/proc.go:208 +0x205 fp=0xc000263fe0 sp=0xc000263f88 pc=0x403cae5
runtime.goexit()
	runtime/asm_amd64.s:1371 +0x1 fp=0xc000263fe8 sp=0xc000263fe0 pc=0x4074541

goroutine 1 [running, locked to thread]:
runtime.asmcgocall(0x4075d40, 0xc0002635a0)
	runtime/asm_amd64.s:652 +0x42 fp=0xc000263558 sp=0xc000263550 pc=0x40741a2
runtime.libcCall(0x4075d40, 0xc0002635a0, 0x4b2f700)
	runtime/sys_libc.go:48 +0x6c fp=0xc000263588 sp=0xc000263558 pc=0x405baec
runtime.walltime1(0x0, 0x0)
	runtime/sys_darwin.go:270 +0x4a fp=0xc0002635c0 sp=0xc000263588 pc=0x405b46a
runtime.walltime(...)
	runtime/time_nofake.go:23
time.now(0x0, 0xc000263628, 0x4010bb8)
	runtime/timestub.go:16 +0x25 fp=0xc0002635f0 sp=0xc0002635c0 pc=0x40717e5
time.Now(0x10000c000263601, 0xc000240aa0, 0xc000263648)
	time/time.go:1067 +0x26 fp=0xc000263618 sp=0xc0002635f0 pc=0x40d3d46
github.com/lucas-clemente/quic-go/internal/wire.init.1()
	github.com/lucas-clemente/quic-go@v0.19.3/internal/wire/transport_parameters.go:22 +0x26 fp=0xc000263658 sp=0xc000263618 pc=0x4891ea6
runtime.doInit(0x54b3ae0)
	runtime/proc.go:6309 +0xec fp=0xc0002637a8 sp=0xc000263658 pc=0x404a86c
runtime.doInit(0x54ae7e0)
	runtime/proc.go:6286 +0x72 fp=0xc0002638f8 sp=0xc0002637a8 pc=0x404a7f2
runtime.doInit(0x54b7580)
	runtime/proc.go:6286 +0x72 fp=0xc000263a48 sp=0xc0002638f8 pc=0x404a7f2
runtime.doInit(0x54b9660)
	runtime/proc.go:6286 +0x72 fp=0xc000263b98 sp=0xc000263a48 pc=0x404a7f2
runtime.doInit(0x54bb1c0)
	runtime/proc.go:6286 +0x72 fp=0xc000263ce8 sp=0xc000263b98 pc=0x404a7f2
runtime.doInit(0x54b8a20)
	runtime/proc.go:6286 +0x72 fp=0xc000263e38 sp=0xc000263ce8 pc=0x404a7f2
runtime.doInit(0x54ba320)
	runtime/proc.go:6286 +0x72 fp=0xc000263f88 sp=0xc000263e38 pc=0x404a7f2
runtime.main()
	runtime/proc.go:208 +0x205 fp=0xc000263fe0 sp=0xc000263f88 pc=0x403cae5
runtime.goexit()
	runtime/asm_amd64.s:1371 +0x1 fp=0xc000263fe8 sp=0xc000263fe0 pc=0x4074541

goroutine 19 [chan receive]:
github.com/syncthing/notify.(*recursiveTree).dispatch(0xc0001c0640)
	github.com/syncthing/notify@v0.0.0-20210308121556-f45149b04939/tree_recursive.go:125 +0xc7
created by github.com/syncthing/notify.newRecursiveTree
	github.com/syncthing/notify@v0.0.0-20210308121556-f45149b04939/tree_recursive.go:119 +0x13b

goroutine 20 [syscall, locked to thread]:
github.com/syncthing/notify._Cfunc_CFRunLoopRun()
	_cgo_gotypes.go:229 +0x3c
github.com/syncthing/notify.init.1.func1()
	github.com/syncthing/notify@v0.0.0-20210308121556-f45149b04939/watcher_fsevents_cgo.go:72 +0x3f
created by github.com/syncthing/notify.init.1
	github.com/syncthing/notify@v0.0.0-20210308121556-f45149b04939/watcher_fsevents_cgo.go:63 +0x4e

goroutine 21 [sleep]:
time.Sleep(0x1dcd6500)
	runtime/time.go:193 +0xd2
github.com/syncthing/syncthing/lib/dialer.init.1.func2()
	github.com/syncthing/syncthing/lib/dialer/internal.go:44 +0x2a
created by github.com/syncthing/syncthing/lib/dialer.init.1
	github.com/syncthing/syncthing/lib/dialer/internal.go:43 +0x15f

rax    0x7fff678d7290
rbx    0x2d900cd0
rcx    0x0
rdx    0x0
rdi    0x7fff678d7400
rsi    0x0
rbp    0x7fff5fbff450
rsp    0x7fff5fbff438
r8     0x7fff678c004c
r9     0x0
r10    0x7fff5fbff228
r11    0x7fff678d7400
r12    0x1
r13    0x1
r14    0x7fff678d7400
r15    0xffffffffffffffff
rip    0x7fff6789e075
rflags 0x246
cs     0x2b
fs     0x0
gs     0x0
2021-08-02 19:01:20.398 Syncthing[7417:49189192] Syncthing daemon terminated (exit code 2)
2021-08-02 19:01:20.398 Syncthing[7417:49189192] Delaying daemon startup by 10.0 s
```

This is due to `clock_gettime` not existing on MacOS 10.11.6, which is what I'm using. Given that your stated requirement is "10.10 or later", maybe you could fix this?¹ Thanks.

---

¹ By which I mean, making it work on 10.11.6, rather than - for example - changing the stated requirements.

**Comment by xor-gate** [comment]
This issue is related to the already closed #148. As mentioned in the FAQ on the main page you need macOS 10.12 or higher. We will not support lower versions or you need to install the latest supported [v1.13.1-1](https://github.com/syncthing/syncthing-macos/releases/tag/v1.13.1-1) version. Or if you are up to an adventure you could compile latest syncthing with a golang compiler supporting macOS 10.11 but then your are on your own. Sorry!

**Comment by xor-gate** [comment]
Forgotten to mention the main page (README.md) has been updated with correct information which macOS version is required.

**Comment by Sod-Almighty** [comment]
Did you *see* my footnote?

**Comment by xor-gate** [comment]
Yes
